### ISSUE TITLE
Version without swoole

### ISSUE THREAD

**Issue by Mewgood** [KejawenLab/SemartApiSkeleton#138]
Hi,

Would it be too much to ask for a version that doesn't depend on swoole?

**Comment by ad3n** [comment]
@Mewgood do you have concern about swoole? i use open swoole instead of official swoole if you have concern. If there's not enough for you, you can change the runtime using nginx or anything easily by change the [runtime class](https://symfony.com/doc/current/components/runtime.html#selecting-runtimes)

**Comment by Mewgood** [comment]
Swoole just seems like a strong dependency compared to the benefits.
